# Site
name: "luizeof"
title: "luizeof"
description: "Wordpress / PHP / Flutter"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
google_analytics: "UA-154888688-1"
disqus: "luizeof"
include: ["_pages"]
permalink: /:title/

sass:
  style: compressed

# Authors
authors:
  luizeof:
    name: luizeof
    display_name: Luiz Eduardo
    gravatar: 105090f00e4e22a9375db598c1ede0a4
    email: luizeof@gmail.com
    web: https://www.luizeof.com.br
    twitter: https://twitter.com/luizeof
    description: "Desenvolvedor Web desde 2005, Entusiasta do Flutter, Mantnedor do Docker Mautic e Devops na Powertic"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-minifier

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 12
paginate_path: /page:num/

# Other
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "pt-BR"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      lang: "pt-BR"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

jekyll-minifier:
  preserve_php: true # Default: false
  remove_spaces_inside_tags: true # Default: true
  remove_multi_spaces: true # Default: true
  remove_comments: true # Default: true
  remove_intertag_spaces: true # Default: false
  remove_quotes: false # Default: false
  compress_css: true # Default: true
  compress_javascript: true # Default: true
  compress_json: false # Default: true
  simple_doctype: false # Default: false
  remove_script_attributes: false # Default: false
  remove_style_attributes: false # Default: false
  remove_link_attributes: false # Default: false
  remove_form_attributes: false # Default: false
  remove_input_attributes: false # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false # Default: false
  remove_https_protocol: false # Default: false
  preserve_line_breaks: false # Default: false
  simple_boolean_attributes: false # Default: false
  compress_js_templates: false # Default: false
  preserve_patterns: # Default: (empty)
  uglifier_args:

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-0573778318030674"
adsense-data-ad-slot: "2833836650"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
