#!/bin/bash

clear

find assets/images/ -name "*.jpg" -exec jpegoptim -m80 -o -p --strip-all {} \;

find assets/images/ -type f -name '*.png' -exec sh -c 'cwebp -q 75 $1 -o "${1%.png}.webp"' _ {} \;

find assets/images/ -type f -name '*.jpg' -exec sh -c 'cwebp -q 75 $1 -o "${1%.jpg}.webp"' _ {} \;

find assets/images/ -type f -name '*.jpeg' -exec sh -c 'cwebp -q 75 $1 -o "${1%.jpeg}.webp"' _ {} \;

rm -rf _site

rm -rf _out

jekyll clean

jekyll build

cp -rf _site/ _out/

minify -r -o _out/ _site
